### ISSUE TITLE
Support a container runtime v2

### ISSUE THREAD

**Issue by sboeuf** [cri-o/cri-o#1945]
Based on https://github.com/kata-containers/runtime/issues/907, the idea is to end up with a v2 of what is implemented by `oci.Runtime` today, by proposing an internal Go interface that would allow for several versions of this same interface. The version 1 being the conmon implementation assuming an OCI CLI binary as the container runtime. The version being a more generic implementation proposing what's done by containerd-shim-v2.

In order to reach this goal, here are 4 big steps:
- [x] Move container implementations from lib to oci package so that they are all implemented by the `oci.Runtime` structure. #1946
- [x] Switch the `oci.Runtime` structure into a Go interface. And use the current `oci.Runtime` implementation as the v1 implementation of this new Go interface. #1989
- [x] Implement v2 so that it complies with containerd-shim-v2 interface, as a VM based friendly implementation. #2024 
- [ ] Add support for `crio` restart. We need to support containers and pod to be restored. #2112
- [ ] Move the definition of the containerd-shim-v2 interface to a more neutral repo since it would be used both by containerd and CRI-O at this point.
