### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#1971]
Hey,

During my digging through the cri-o code I found out that the unit test coverage could be improved in multiple places. I think I can start with this task but would also suggest some other changes which are related to that:

- use [ginkgo](https://github.com/onsi/ginkgo) and [gomega](https://onsi.github.io/gomega/) for refactored  and newly added (unit) tests
- refactor some methods wich a high cyclomatic complexity when writing these tests
- introduce a mocking framework to make the tests independent and durable

What do you think? :innocent: 

#### Things to be done
- [x] Add ginkgo / gomega as test dependency (#1974)
    - [x] Add `pkg` unit tests and mocking dependencies (#1992)
      - [x] Add continuous coverage report (#2048)
      - [x] Add `utils` unit tests (#1993)
      - [x] Add `sandbox` unit tests (#1996)
      - [x] Add `oci` unit tests (#2015)
      - [x] Add `lib` unit tests (#1994)
        - [x] Add `server` unit tests (#2002, #2293)
            - [ ] Refactor `server/sandbox_run_linux.go` and extend unit testing
            - [ ] Refactor `server/container_create_linux.go` and extend unit testing

Related issues: #2008, #2009

**Comment by mrunalp** [comment]
Sure :+1: :)

**Comment by rhatdan** [comment]
@saschagrunert I take it you are continue to work on this.  Great.

**Comment by saschagrunert** [comment]
@rhatdan Sure, I will finish it up :)

**Comment by saschagrunert** [comment]
The overall test implementation is done and closed with #2407 for now. A higher coverage can be achieved with the mentioned refactoring of the huge functions in `server/sandbox_run_linux.go` and `server/container_create_linux.go`. I will follow up on this without any particular issue.
